<<<<<<< HEAD
# Generated by Django 4.1 on 2025-08-22 17:52
=======
# Generated by Django 4.1 on 2025-08-20 18:36
>>>>>>> b1aa38ff449458c3b22cf9996c9820a4fbcff282

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> b1aa38ff449458c3b22cf9996c9820a4fbcff282
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
    ]
