# Generated by Django 4.1 on 2025-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
